### ISSUE TITLE
Vie et Volonté ont +2 côté PJ vs côté MJ

### ISSUE THREAD

**Issue by ElethornGM** [fibreville/minotaure#117]
Avec la dernière version (avec la jauge de volonté) lorsqu'un personnage est créé, il a +2 points de vie et +2 points de volonté lorsqu'on le regarde côté joueur.
J'utilises chrome. J'ai vidé le cache.

![image](https://user-images.githubusercontent.com/77462012/122448433-0972bd00-cfa5-11eb-861a-2140e1f26200.png)

![image](https://user-images.githubusercontent.com/77462012/122448483-168fac00-cfa5-11eb-896e-0c8170372bd5.png)

**Comment by uurshin** [comment]
Résolu depuis la 2.7.
