### ISSUE TITLE
Bug de statistique si création de personnage sans sélectionner une option

### ISSUE THREAD

**Issue by ElethornGM** [fibreville/minotaure#118]
Au niveau de la création de personnage, si je clique sur "Partir à l'aventure" sans sélectionner l'une des options en terme de statistique, j'obtiens des stats bizarres : 

![image](https://user-images.githubusercontent.com/77462012/122448590-32934d80-cfa5-11eb-8302-f01cffe22cbf.png)

![image](https://user-images.githubusercontent.com/77462012/122448685-522a7600-cfa5-11eb-89bf-6e7b31383990.png)

Voir Test 2 et Test 4 : 

![image](https://user-images.githubusercontent.com/77462012/122448803-6f5f4480-cfa5-11eb-9201-632ce7bd6f5b.png)

**Comment by uurshin** [comment]
Résolu depuis la 2.7.
