### ISSUE TITLE
Définir les paramètres de connexion dans un fichier config.php

### ISSUE THREAD

**Issue by twaiiiin** [fibreville/minotaure#25]
Bonjour,

J'ai une petite suggestion pour simplifier la procédure d'installation et de configuration de l'app : il serait peut-être préférable de remplacer `serveur-mysql`, `nombase`, `login `et `mdp `par des constantes dans le fichier `connexion.php`. Ces constantes pourraient alors être définies dans un fichier `config.php` séparé. C'est plus clair, plus propre et sécurisé (pour les débutants) que modifier un fichier du cœur de l'app.

Qu'est-ce que vous en pensez ?

**Comment by uurshin** [comment]
Oui c'est clairement une bonne idée !
Bon ça veut dire que je dois refaire la vidéo d'installation sur l'hébergeur gratuit mais comme de toute façon je dois rajouter autre chose suite à la 2.3 c'est pas bien grave.
Tu fais une pull request ? Pense à intégrer $tpm_path dans la liste des variables.

**Comment by uurshin** [comment]
Si tu n'es pas en mesure de coder ça, je peux le faire pour une future version mais ce sera pas tout de suite du coup.

**Comment by uurshin** [comment]
Je n'ai pas fait de fichier séparé mais j'ai isolé en haut du fichier les éléments à modifier (avec le chemin des fichiers temporaire et les paramètres de langue).
