### ISSUE TITLE
Découpage de ecran.php en fonctions

### ISSUE THREAD

**Issue by uurshin** [fibreville/minotaure#34]
Comme suggéré par @lp177, ce serait bien de découper le code de ecran.php en fonctions pour le rendre plus clair.

**Comment by lp177** [comment]
https://github.com/fibreville/atrpg/pull/44/commits/6c3be70ce68c8a3653661ed108ebd8818f5c5a13
y a encore un peut de découpe à faire si ça vous tente sur la partie affichage et ça pourrais être si vous voulez la garder de propager la fonction avoid_form_resending_on_refresh sur les formulaires utilisateurs.

**Comment by uurshin** [comment]
Du coup j'ai géré la partie "avoid_form_resending_on_refresh" différemment (en js).
