### ISSUE TITLE
[Front] Décalage du placeholder de l'input

### ISSUE THREAD

**Issue by vouiv-re** [fibreville/minotaure#88]
Non-important et non-urgent.
Sur chrome uniquement.

Décalage du placeholder des inputs sur la page de gestion des tags.

![1112](https://user-images.githubusercontent.com/39560791/110251626-a921b780-7f81-11eb-9263-d923497278a1.png)

**Comment by uurshin** [comment]
Résolu dans la 2.7.0-rc.
