### ISSUE TITLE
Changer de couleur impossible sous Mozilla

### ISSUE THREAD

**Issue by Mokui** [fibreville/minotaure#92]
Sur Mozilla on a ce comportement :
![image](https://user-images.githubusercontent.com/26810364/112343252-3d4e8700-8cc3-11eb-8e70-ce9bd7c50684.png)

Sur chrome on a ça : 
![image](https://user-images.githubusercontent.com/26810364/112343366-5a835580-8cc3-11eb-8d61-6d0443b44bce.png)

**Comment by uurshin** [comment]
Hello @Mokui. Ce n'est probablement pas qu'un problème de changement de couleur, ta capture mozilla (tu veux dire Firefox ?) présente plein de souci d'affichage.
Je stream sur Firefox et je n'ai pas de souci. Tu peux me contacter sur Discord qu'on regarde ensemble : Nishruu#5735 ?
Sinon on se fait un partage d'écran ailleurs si tu n'utilises pas Discord.

**Comment by uurshin** [comment]
Je clôture le ticket en l'absence de retour. La capture montre plutôt clairement un problème de cache. Je ne reproduis pas sur firefox et je n'ai reçu aucun autre témoignage dans ce sens.
