### ISSUE TITLE
"Dossier des fichiers temporaires introuvable" avec 000webhostapp

### ISSUE THREAD

**Issue by MelchiorDussol** [fibreville/minotaure#93]
Bonjour,

j'obtiens ce message d'erreur après avoir modifié les infos dans le fichier "connexion.php".
Je précise que j'ai bien changé le $tmp_path en './tmp'

Je précise que je n'ai aucune notion en hébergement et que j'ai suivi le tuto vidéo.

Merci !

**Comment by MelchiorDussol** [comment]
Je pense avoir trouvé la solution : il faut créer un dossier "tmp" dans le dossier "public_html"

**Comment by uurshin** [comment]
Hello ! Il est tout à fait possible que pour ton hébergement ce soit "/tmp" qu'il faille ajouter, et pas "./tmp". Mais ta solution fonctionne aussi.
